/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simuladorautomotriz;

/**
 *
 * @author Valeria
 */
public class simulador extends javax.swing.JFrame {

    /**
     * Creates new form simulador
     */
    public simulador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        colaBugatti3 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaGanadores = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        colaBugatti2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        colaBugattiRef = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        colaLambo1 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        colaLambo2 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        colaLambo3 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        disminuir = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        colaLamboRef = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        ganador = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ai2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        aumentar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ai1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        accion = new javax.swing.JTextField();
        ganadasBugatti = new javax.swing.JTextField();
        ganadasLambo1 = new javax.swing.JTextField();
        velocidad2 = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        colaBugatti1 = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        colaBugatti3.setEditable(false);
        colaBugatti3.setColumns(20);
        colaBugatti3.setRows(5);
        jScrollPane1.setViewportView(colaBugatti3);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 250, 40));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel3.setText("COLA 2 ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 290, -1, -1));

        listaGanadores.setEditable(false);
        listaGanadores.setColumns(20);
        listaGanadores.setRows(5);
        jScrollPane3.setViewportView(listaGanadores);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 270, 50));

        colaBugatti2.setEditable(false);
        colaBugatti2.setColumns(20);
        colaBugatti2.setRows(5);
        jScrollPane4.setViewportView(colaBugatti2);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 250, 40));

        colaBugattiRef.setEditable(false);
        colaBugattiRef.setColumns(20);
        colaBugattiRef.setRows(5);
        jScrollPane5.setViewportView(colaBugattiRef);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 250, 40));

        colaLambo1.setEditable(false);
        colaLambo1.setColumns(20);
        colaLambo1.setRows(5);
        jScrollPane6.setViewportView(colaLambo1);

        jPanel2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, 250, 40));

        colaLambo2.setEditable(false);
        colaLambo2.setColumns(20);
        colaLambo2.setRows(5);
        jScrollPane7.setViewportView(colaLambo2);

        jPanel2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 280, 250, 40));

        colaLambo3.setEditable(false);
        colaLambo3.setColumns(20);
        colaLambo3.setRows(5);
        jScrollPane8.setViewportView(colaLambo3);

        jPanel2.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 330, 250, 40));

        jLabel13.setText("segundos");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, -1, -1));

        disminuir.setText("DISMINUIR");
        disminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disminuirActionPerformed(evt);
            }
        });
        jPanel2.add(disminuir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, -1, -1));

        colaLamboRef.setEditable(false);
        colaLamboRef.setColumns(20);
        colaLamboRef.setRows(5);
        jScrollPane9.setViewportView(colaLamboRef);

        jPanel2.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 250, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Lista de Ganadores");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, -1, -1));

        ganador.setEditable(false);
        ganador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ganadorActionPerformed(evt);
            }
        });
        jPanel2.add(ganador, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 750, 130, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Buggatti");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        ai2.setEditable(false);
        ai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ai2ActionPerformed(evt);
            }
        });
        jPanel2.add(ai2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 480, 60, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Resultado:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 640, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("AI revisando ID");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 480, -1, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Lamborghini");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 580, -1, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel7.setText("REFUERZO");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel8.setText("COLA 2 ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel11.setText("COLA 1 ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel17.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel17.setText("COLA 3 ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel22.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel22.setText("COLA 3 ");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 340, -1, -1));

        jLabel14.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel14.setText("REFUERZO");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        aumentar.setText("AUMENTAR");
        aumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentarActionPerformed(evt);
            }
        });
        jPanel2.add(aumentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel9.setText("COLA 1 ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 240, -1, -1));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, -1, -1));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        jLabel12.setText(" Carreras Ganadas");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 630, -1, -1));

        jLabel15.setText(" Carreras Ganadas");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        ai1.setEditable(false);
        ai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ai1ActionPerformed(evt);
            }
        });
        jPanel2.add(ai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 60, 40));

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("                                                    COPA PISTON ");
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1330, 60));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo bugatti.png"))); // NOI18N
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 190, 100));

        accion.setEditable(false);
        accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionActionPerformed(evt);
            }
        });
        jPanel2.add(accion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 640, 110, 30));

        ganadasBugatti.setEditable(false);
        ganadasBugatti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ganadasBugattiActionPerformed(evt);
            }
        });
        jPanel2.add(ganadasBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 90, 30));

        ganadasLambo1.setEditable(false);
        ganadasLambo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ganadasLambo1ActionPerformed(evt);
            }
        });
        jPanel2.add(ganadasLambo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 650, 90, 30));

        velocidad2.setEditable(false);
        velocidad2.setText("0");
        velocidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velocidad2ActionPerformed(evt);
            }
        });
        jPanel2.add(velocidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 70, 30));

        colaBugatti1.setEditable(false);
        colaBugatti1.setColumns(20);
        colaBugatti1.setRows(5);
        jScrollPane10.setViewportView(colaBugatti1);

        jPanel2.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 250, 40));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lambo logo.png"))); // NOI18N
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 80, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setText("AI revisando ID");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo copa piston.png"))); // NOI18N
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setText("Cambiar Velocidad");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fancesco cars.png"))); // NOI18N
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rayo cars.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 600, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1320, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void disminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disminuirActionPerformed
         if (SimuladorAutomotriz.velocidad<15000){
            SimuladorAutomotriz.velocidad = SimuladorAutomotriz.velocidad + 1000;
            simulador.velocidad2.setText(String.valueOf(SimuladorAutomotriz.velocidad));
        }else{
            
        }

    }//GEN-LAST:event_disminuirActionPerformed

    private void ganadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ganadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ganadorActionPerformed

    private void ai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ai2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ai2ActionPerformed

    private void aumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentarActionPerformed
        if (SimuladorAutomotriz.velocidad>2000){
            SimuladorAutomotriz.velocidad = SimuladorAutomotriz.velocidad - 1000;
            System.out.println(SimuladorAutomotriz.velocidad);
            simulador.velocidad2.setText(String.valueOf(SimuladorAutomotriz.velocidad));
        }else{
            
        }
    }//GEN-LAST:event_aumentarActionPerformed

    private void ai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ai1ActionPerformed

    private void accionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accionActionPerformed

    private void ganadasBugattiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ganadasBugattiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ganadasBugattiActionPerformed

    private void ganadasLambo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ganadasLambo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ganadasLambo1ActionPerformed

    private void velocidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velocidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velocidad2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simulador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static volatile javax.swing.JTextField accion;
    public static volatile javax.swing.JTextField ai1;
    public static volatile javax.swing.JTextField ai2;
    private javax.swing.JButton aumentar;
    public static volatile javax.swing.JTextArea colaBugatti1;
    public static volatile javax.swing.JTextArea colaBugatti2;
    public static volatile javax.swing.JTextArea colaBugatti3;
    public static volatile javax.swing.JTextArea colaBugattiRef;
    public static volatile javax.swing.JTextArea colaLambo1;
    public static volatile javax.swing.JTextArea colaLambo2;
    public static volatile javax.swing.JTextArea colaLambo3;
    public static volatile javax.swing.JTextArea colaLamboRef;
    private javax.swing.JButton disminuir;
    public static volatile javax.swing.JTextField ganadasBugatti;
    public static volatile javax.swing.JTextField ganadasLambo1;
    public static volatile javax.swing.JTextField ganador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public static volatile javax.swing.JTextArea listaGanadores;
    public static volatile javax.swing.JTextField velocidad2;
    // End of variables declaration//GEN-END:variables
}
